name: Continuous-Delivery

on:
    push:
        branches:
          - master
    pull_request:
        branches:
          - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build --configuration Release
        
      - name: Pack
        run: dotnet pack --configuration Release
        
      - name: Deploy
        run: dotnet nuget push src/TWord/bin/Release/*.nupkg -s nuget.org -k ${{ secrets.NUGET_TOKEN }}